name: C/C++ CI

on:
  push:
    branches: [ "1.20.60" ]
  pull_request:
    branches: [ "1.20.60" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
      run: ./configure
      run: make
      run: make check
      run: make distcheck
